/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chpc;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
  }
}
